### ISSUE TITLE
Players kicked when interacting with containers

### ISSUE THREAD

**Issue by CommanderRichter** [quiltservertools/DeltaLogger#57] opened 2021-03-30 17:41 UTC
**Describe the bug**
When players interact with a specific container they are kicked/disconnected by the server. They are not able to interact/break the container. multiple players are unable to interact with the same container.

**To Reproduce**
Steps to reproduce the behavior: Not sure, has happened multiple times and we are not sure why.

**Expected behavior**
Players not have to be kicked by the server

**Screenshots**

**Specs:**
 - Version [eg. DeltaLogger v1.1.2]
 - OS: [Linux]
 - Java version [8]
 - Mods:
 - Fabric API 0.32.0
 - Fabric Per player spawns 1.0.0
 - Lithium 1.16.5-0.6.4
 - Phosphor 1.16.3-0.7.1

**Logs**
[2021-03-30 13:12:42] [Server thread/INFO]: Divercat42 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

**Comment by EvilSquirrelGuy** [comment] 2021-03-30 17:47
Possible duplicate of #41

**Comment by CommanderRichter** [comment] 2021-03-30 18:31
Read and was aware of 41 but since player's don't even have an opportunity to add or remove items felt like a more distinct issue.

**Closed** 2021-05-02 13:23 UTC
Labels: invalid, other mod's issue
